from collections.abc import Sequence
from contextlib import AbstractContextManager
from typing import Protocol

from network_history.models import Activity, CollectorState, Device, HistoryPage, HistoryRow


class Repository(Protocol):
    """Backend boundary. Imports and their checkpoint must commit atomically."""

    def initialize(self) -> None: ...
    def collection_lock(self) -> AbstractContextManager[bool]: ...
    def collection_running(self) -> bool: ...
    def get_state(self) -> CollectorState: ...
    def commit_import(
        self, rows: Sequence[HistoryRow], expected_checkpoint: int, successful_at: int
    ) -> None: ...
    def record_error(self, error: str) -> None: ...
    def recent_activity(self, mac: str | None = None, limit: int = 100) -> list[Activity]: ...
    def list_devices(self) -> list[Device]: ...
    def update_device(self, mac: str, friendly_name: str, notes: str | None) -> bool: ...

    def find_device(self, mac: str) -> Device | None: ...
    def devices_seen_between(self, start: int, end: int) -> list[Device]: ...
    def activity_page(
        self,
        mac: str,
        start: int,
        end: int,
        limit: int,
        *,
        after: tuple[int, int] | None = None,
        snapshot_id: int | None = None,
    ) -> HistoryPage: ...
